// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdV8c123IT9k9zHmPYO20ux1EnPKOsK7o',
    appId: '1:328013600361:web:072e3b2a4b2700705cf4f8',
    messagingSenderId: '328013600361',
    projectId: 'milestone-1-858a9',
    authDomain: 'milestone-1-858a9.firebaseapp.com',
    storageBucket: 'milestone-1-858a9.firebasestorage.app',
    measurementId: 'G-PLVT8FTK97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoeO4yvmw2Pvqt05NKKBcydxijK_MLzl8',
    appId: '1:328013600361:android:8c1a22b75ad2b25e5cf4f8',
    messagingSenderId: '328013600361',
    projectId: 'milestone-1-858a9',
    storageBucket: 'milestone-1-858a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPqnwlOFIq-2aba6ltz4M8JWHz1BxgHvU',
    appId: '1:328013600361:ios:b86b6018542d08045cf4f8',
    messagingSenderId: '328013600361',
    projectId: 'milestone-1-858a9',
    storageBucket: 'milestone-1-858a9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPqnwlOFIq-2aba6ltz4M8JWHz1BxgHvU',
    appId: '1:328013600361:ios:b86b6018542d08045cf4f8',
    messagingSenderId: '328013600361',
    projectId: 'milestone-1-858a9',
    storageBucket: 'milestone-1-858a9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdV8c123IT9k9zHmPYO20ux1EnPKOsK7o',
    appId: '1:328013600361:web:1e1435a87efbd1195cf4f8',
    messagingSenderId: '328013600361',
    projectId: 'milestone-1-858a9',
    authDomain: 'milestone-1-858a9.firebaseapp.com',
    storageBucket: 'milestone-1-858a9.firebasestorage.app',
    measurementId: 'G-9JYQ57GWDK',
  );
}
